# Generated by Django 4.1.7 on 2023-05-16 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('question', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=50)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.foldermodel')),
            ],
            bases=('base.basemodel',),
        ),
    ]
