# Generated by Django 4.1.7 on 2023-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizchoicesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizchoicesmodel',
            name='type',
            field=models.CharField(default='QUIZ', max_length=50),
        ),
        migrations.AddField(
            model_name='quizquestionsmodel',
            name='type',
            field=models.CharField(default='QUIZ', max_length=50),
        ),
    ]
