# Generated by Django 4.1.7 on 2023-05-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizchoicesmodel_type_quizquestionsmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchoicesmodel',
            name='answer',
        ),
        migrations.AddField(
            model_name='quizchoicesmodel',
            name='answer_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quizchoicesmodel',
            name='answer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quizchoicesmodel',
            name='answer_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quizchoicesmodel',
            name='answer_4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
