# Generated by Django 4.1.7 on 2023-05-18 14:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('folders', '0001_initial'),
        ('quizzes', '0004_remove_quizchoicesmodel_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('choice', models.CharField(max_length=255)),
                ('type', models.CharField(default='CHOICES', max_length=50)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(default='QUESTIONS', max_length=50)),
                ('choices', models.ManyToManyField(to='quizzes.choicemodel')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(default='QUIZ', max_length=50)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.foldermodel')),
                ('questions', models.ManyToManyField(to='quizzes.questionsmodel')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.RemoveField(
            model_name='quizquestionsmodel',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='quizquestionsmodel',
            name='folder_id',
        ),
        migrations.DeleteModel(
            name='QuizChoicesModel',
        ),
        migrations.DeleteModel(
            name='QuizQuestionsModel',
        ),
    ]
