# Generated by Django 4.1.7 on 2023-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_choicemodel_questionsmodel_quizmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
