# Generated by Django 4.1.7 on 2023-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_quizmodel_questions_quizmodel_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
