# Generated by Django 4.1.7 on 2023-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
