# Generated by Django 4.1.7 on 2023-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemodel',
            name='type',
            field=models.CharField(default='MODULE', max_length=50),
        ),
    ]
