# Generated by Django 4.1.7 on 2023-03-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
