# Generated by Django 4.1.7 on 2023-03-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
