# Generated by Django 4.1.7 on 2023-05-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='name',
            new_name='comment',
        ),
    ]
