# Generated by Django 4.1.7 on 2023-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_name_commentmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
